# Generated by Django 2.0.7 on 2018-08-23 16:21

import CulturalEvent.models
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('summary', models.TextField()),
                ('over18', models.NullBooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=120, null=True)),
                ('File', models.ImageField(blank=True, height_field='CE_ImageHeight', null=True, upload_to=CulturalEvent.models.upload_location, width_field='CE_ImageWidth')),
                ('CE_ImageHeight', models.IntegerField(default=0)),
                ('CE_ImageWidth', models.IntegerField(default=0)),
                ('CE_type', models.CharField(choices=[('1', 'generico'), ('2', 'musica'), ('3', 'teatro'), ('4', 'danca'), ('5', 'cinema'), ('6', 'patinacao'), ('7', 'corrida'), ('8', 'acampamento'), ('9', 'encontro de jovens')], default='generico', max_length=100)),
                ('CE_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('CE_phonenumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True)),
                ('CE_isWhatsApp', models.NullBooleanField()),
            ],
        ),
    ]
