# Generated by Django 2.0.7 on 2018-08-24 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CulturalEvent', '0003_auto_20180823_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturalevent',
            name='CE_DateAndTipe',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 24, 13, 35, 37, 338557)),
        ),
    ]
