# Generated by Django 2.0.7 on 2018-08-24 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CulturalEvent', '0004_culturalevent_ce_dateandtipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culturalevent',
            name='CE_DateAndTipe',
        ),
        migrations.AddField(
            model_name='culturalevent',
            name='CE_Date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 8, 24, 13, 40, 6, 249391)),
        ),
        migrations.AddField(
            model_name='culturalevent',
            name='CE_Time',
            field=models.TimeField(blank=True, default=datetime.datetime(2018, 8, 24, 13, 40, 6, 249431)),
        ),
    ]
