# Generated by Django 2.0.7 on 2018-08-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CulturalEvent', '0008_auto_20180824_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalevent',
            name='CE_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='culturalevent',
            name='CE_Time',
            field=models.TimeField(),
        ),
    ]
