# Generated by Django 2.0.7 on 2018-08-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CulturalEvent', '0009_auto_20180824_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalevent',
            name='CE_type',
            field=models.CharField(choices=[('0', 'generico'), ('1', 'musica'), ('2', 'teatro'), ('3', 'danca'), ('4', 'cinema'), ('5', 'patinacao'), ('6', 'corrida'), ('7', 'acampamento'), ('8', 'encontro de jovens')], default='generico', max_length=100),
        ),
    ]
