# Generated by Django 2.0.7 on 2018-08-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CulturalEvent', '0021_auto_20180824_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalevent',
            name='CE_Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='culturalevent',
            name='CE_Time',
            field=models.TimeField(null=True),
        ),
    ]
